### ISSUE TITLE
Infinite Loop if auto_open_serial = 1

### ISSUE THREAD

**Issue by haydenflinner** [jplaut/vim-arduino-ino#7]
When ArduinoSerialMonitor() is called, it calls ArduinoDeploy(), which deploys and then calls ArduinoSerialMonitor(), which results in an infinite loop.

**Comment by jplaut** [comment]
Can you provide file/line number for where you see this issue? The serial monitor script simply opens a screen that listens to the Arduino's serial port. It does not call ArduinoDeploy() from within the script.

**Comment by haydenflinner** [comment]
That's because you fixed it when you merged request #8 ;)
